apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: es-secret-store
spec:
  provider:
    vault:
      server: "http://hashicorp-vault-0.hashicorp-vault-internal.vault.svc.cluster.local:8200"
      path: "platform"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-role"
