---
apiVersion: v1
kind: Secret
metadata:
  namespace: controller-vault
  name: vault-auth
  annotations:
    kubernetes.io/service-account.name: hashicorp-vault
type: kubernetes.io/service-account-token
