name: provisioning
run-name: Terraform provisioning

on:
  workflow_dispatch:
    inputs:
      provider:
        description: 'Cloud provider'
        required: true
        type: string
        default: azure
        
  push:
    branches:
      - main

jobs:
  callTerraformScan:
    name: Scan
    uses: ./.github/workflows/terraform-scan.yml

  # STARTS AWS
  callTerraformAws:
    needs: callTerraformScan
    name: AwsInputs
    # if:  inputs.provider == 'aws' && needs.callTerraformScan.result == 'success'
    if:  inputs.provider == 'aws' && needs.callTerraformScan.result == 'success'
    uses: ./.github/workflows/terraform-aws.yml
    secrets:
        AWS_ACCESS_KEY_ID:  "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY:  "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        AWS_DEFAULT_REGION:  "${{ secrets.AWS_DEFAULT_REGION }}"


  # STARTS AZURE
  callTerraformAzure:
    needs: callTerraformScan
    name: AzureInputs 
    uses: ./.github/workflows/terraform-azure.yml
    if: needs.callTerraformScan.result == 'success'
    secrets:
      ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
      ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
      ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"
