---
name: scan-golang
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  scanGolang:
    name: scanGolang
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'config'
          scan-ref: './src'
          hide-progress: true
          format: 'table'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'MEDIUM,HIGH,CRITICAL'

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './src'
          format: 'table'
          severity: 'MEDIUM,HIGH,CRITICAL'

  # call_deployment:
  #   name: Provisioning
  #   uses: ./.github/workflows/main.yml
  #   needs: scanGolang
  #   if: ${{ needs.scanGolang.result }} == 'success'
