name: start
run-name: Load project

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Load'
    runs-on: ubuntu-latest
   
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Date
      run: date
