---
  name: scan-terraform
  on:
    workflow_dispatch:
    push:
      branches:
        - main
  
  jobs:
    scanTerraform:
      name: scanTerraform
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Run Trivy vulnerability scanner in IaC mode
          uses: aquasecurity/trivy-action@0.20.0
          with:
            scan-type: 'config'
            scan-ref: './infra'
            hide-progress: true
            format: 'sarif'
            output: 'trivy-results.sarif'
            exit-code: '1'
            ignore-unfixed: true
            severity: 'MEDIUM,HIGH,CRITICAL'
  
    call_provisioning:
      name: Provisioning
      uses: ./.github/workflows/main.yml
      needs: scanTerraform
      if: ${{ needs.scanTerraform.result }} == 'success'
  