crds:
  install: true
global:
  # AJUSTAR AS TAGS
  domain: synera.com.br
  {%- if values.labels %}
  additionalLabels:
    {% for key, value in values.labels %}
      ${{- key }}: "${{ value }}"
    {% endfor -%}
  {%- else  %}  
  additionalLabels:  {}
  {%- endif  %}


configs:
  styles: |
    .nav-bar {
      background: #222;
    }
    .sidebar {
       background-color: #222;
     }
    .sidebar__logo span {
      display: "Synera sempre ao seu lado";
    }
    .sidebar__logo img {
      content: url(https://synera.com.br/wp-content/uploads/2022/09/logo-normal-branco-150x150.png);
    }
    .status-bar__segment__fill {
             background-color: #222;
      background: #222;
    }

  cm:
    ui.bannercontent: Synera, deploy de forma inteligente
    ui.bannerurl: "https://www.synera.com.br"
    ui.bannerpermanent: "true"
    ui.bannerposition: "top"

notifications:
  enabled: true
  name: notifications-controller
server:
  extraArgs:
    - --insecure
  service:
    type: ClusterIP
  ingress:
    enabled: kong
    ingressClassName: kong
    hostname: gitops.${{ values.projectName | replace(" ", "-") | lower}}.synera.com.br
  extensions:
    enabled: true
    extensionList:
      - name: rollout-extension
        env:
          - name: EXTENSION_URL
            value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.5/extension.tar
