---
apiVersion: v1
kind: Secret
metadata:
  name: exdns
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  url: https://kubernetes-sigs.github.io/external-dns
  type: helm
  name: exdns