---
apiVersion: v1
kind: Secret
metadata:
  name: hashicorp
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  url: https://helm.releases.hashicorp.com
  type: helm
  name: hashicorp