---
apiVersion: v1
kind: Secret
metadata:
  name: kong
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  url: https://charts.konghq.com
  type: helm
  name: kong