apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.projectName | replace(" ", "-") | lower}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif  %}
spec:
  type: service
  lifecycle: production
  owner: ${{ values.userName | lower}}
  system: platform-develop

