site_name: 'plataforma-infra-as-code'
site_description: Developer platform developer for infra as code

nav:
  - Getting Started: index.md
  - Groups structure: groups.md
  - Repository: repository.md
  - GitHub Workflow: workflow.md
  - Terraform: terraform.md
  - Manifests update in Backstage: manifests.md
  - Accesses: accesses.md

plugins:
  - techdocs-core