site_name: 'platform-infra-as-code'
site_description: Developer platform developer for infra as code

nav:
  - Getting Started: docs/index.md
  - Groups structure: docs/groups.md
  - Repository: docs/repository.md
  - GitHub Workflow: docs/workflow.md
  - Terraform: docs/terraform.md
  - Manifests update in Backstage: docs/manifests.md
  - Accesses: docs/accesses.md

plugins:
  - techdocs-core