apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: plataforma-tpl
  title: Plataforma tpl
  description: Template tpl
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: syner
  type: service
  parameters:
    - include: ./templates/tpl/parameters/common/00-user.yaml
    - include: ./templates/tpl/parameters/common/01-project.yaml
    - include: ./templates/tpl/parameters/common/02-repo.yaml

  steps:
    - include: ./templates/tpl/steps/common/00-init.yaml



  output:
    links:
      - title: Documentation
        url: https://platform-demo.synera.com.br/docs/default/template/plataforma-orchestration
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      # - title: Open in catalog
      #   icon: catalog
      #   entityRef: ${{ steps['register'].output.entityRef }}