apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-platform-orchestration
  title: Create Platform Orchestration
  description: This template will create the platform orchestration structure
spec:
  owner: syner
  type: service

  parameters:
    - title: User info
      required:
        - userEmail
        - userName
      properties:
        userName:
          ttile: User name 
          type: string
          description: User logged
          # ui:field: 
        userEmail:
          ttile: Email of user
          type: string
          description: Email of user logged
    - title: Project info
      required:
        - projectName
        - repoUrl
      properties:
        projectName:
          ttile: Project name
          type: string
          description: Project name to be create
        projectLabels:
          ttile: Project labels
          type: string
          description: Set labels for this project
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - synera-br
  steps:
    - id: fetch-catalog
      name: Fetch Catalog
      action: fetch:template
      input:
        url: ../catalog/component
        # targetPath: ./catalog
        values:
          projectName: ${{ parameters.projectName }}
          userName: ${{ parameters.userName }}
          description: description

    - name: Write Catalog information
      action: catalog:write
      input:
        entity:
          apiVersion: 'backstage.io/v1alpha1'
          kind: Component
          metadata:
            name: ${{ parameters.projectName }}
            annotations:
              github.com/project-slug: ${{ parameters.repoUrl | projectSlug }}
          spec:
            type: service
            lifecycle: production
            owner: ${{ parameters.userName }}
        filePath: 'catalog-info.yaml'

    - id: fetch-cicd
      name: Fetch CI/CD
      action: fetch:template
      input:
        url: ../cicd
        targetPath: ./
        values:
          projectName: ${{ parameters.projectName }}
          userName: ${{ parameters.userName }}
          description: description
  
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}


    - id: wait
      name: wait
      action: debug:wait
      input:
        seconds: 60

    - id: dispatch
      name: dispatch
      action: github:actions:dispatch
      input:
        workflowId: full.yaml
        branchOrTagName: master
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
    #     catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      # - title: Open in catalog
      #   icon: catalog
      #   entityRef: ${{ steps['register'].output.entityRef }}